version: "3.9"

services:
  mysql:
    container_name: mysql_testing
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3307"

  php-fpm:
    container_name: php-fpm_testing
    build:
      context: ./php-fpm
    volumes:
      - ./../:/var/www
    ports:
      - "3001:3001"

  nginx:
    container_name: nginx_testing
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/environment/local/sites/:/etc/nginx/sites-available
      - ./nginx/environment/local/conf.d/:/etc/nginx/conf.d
    # - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "81:81"
      - "444:444"
    networks:
      default:
        ipv4_address: 172.10.0.102

networks:
  default:
    external:
      name: docker_default
